# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  backend:
    build:
      context: "D:\\c# projects\\LearningEnglishApp\\Backend"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Backend.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Backend.staticwebassets.runtime.CT.json"
    image: "learning_english_api:dev"
    ports: []
    volumes:
    - "D:\\c# projects\\LearningEnglishApp\\Backend:/app:rw"
    - "D:\\c# projects\\LearningEnglishApp:/src:rw"
    - "C:\\Users\\never\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  frontend:
    build:
      context: "D:\\c# projects\\LearningEnglishApp\\Frontend"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Frontend.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "learning_english_web:dev"
    ports: []
    volumes:
    - "D:\\c# projects\\LearningEnglishApp\\Frontend:/app:rw"
    - "D:\\c# projects\\LearningEnglishApp:/src:rw"
    - "C:\\Users\\never\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
