# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  backend:
    build:
      context: "/Users/ilakonev/RiderProjects/LearningEnglishApp4/Backend"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Backend.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Backend.staticwebassets.runtime.CT.json"
    image: "learning_english_api:dev"
    ports: []
    volumes:
    - "/Users/ilakonev/.nuget/packages:/root/.nuget/packages"
    - "/Users/ilakonev/RiderProjects/LearningEnglishApp4/Backend:/app:rw"
    - "/Users/ilakonev/RiderProjects/LearningEnglishApp4:/src:rw"
    working_dir: "/app"
  frontend:
    build:
      context: "/Users/ilakonev/RiderProjects/LearningEnglishApp4/Frontend"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Frontend.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
    image: "learning_english_web:dev"
    ports: []
    volumes:
    - "/Users/ilakonev/.nuget/packages:/root/.nuget/packages"
    - "/Users/ilakonev/RiderProjects/LearningEnglishApp4/Frontend:/app:rw"
    - "/Users/ilakonev/RiderProjects/LearningEnglishApp4:/src:rw"
    working_dir: "/app"
